
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    post_author_id INTEGER NOT NULL,
    post_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    post_body TEXT NOT NULL,
    FOREIGN KEY (post_author_id) REFERENCES user (id)
);

CREATE TABLE comment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    comment_author_id INTEGER NOT NULL,
    post_id INTEGER NOT NULL,
    comment_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment_body TEXT NOT NULL,
    FOREIGN KEY (comment_author_id) REFERENCES user (id)
);